---
- name: Upgrade packages
  sudo: true
  yum: name=* 
       state=latest

- name: Install required packages
  sudo: true
  yum: name={{ item }}
       state=latest
  with_items:
    - git
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - python-devel
    - python-setuptools
    - gcc
    - firewalld

- name: ensure firewalld is started
  sudo: true
  service: name=firewalld
           state=started
   
- name: create the user group
  group: name={{ user_group }}
         state=present
  sudo: true

- name: add shell user to the user group
  user: name={{ ansible_user_id }} groups={{ user_group }}
        append=yes
  sudo: true

- name: Setup the opt folder
  sudo: true
  file: path=/opt
        owner={{ ansible_user_id }}
        group={{ user_group }}
        state=directory
        mode=0775

- name: Create the src folder
  sudo: true
  file: path=/opt/src
        owner={{ ansible_user_id }}
        group={{ user_group }}
        state=directory
        mode=0775
  when: is_vagrant is not defined or not is_vagrant

- name: Remove system pip and virtualenv
  sudo: true
  yum: name={{ item }}
       state=absent
  with_items:
    - python-pip
    - python-virtualenv

- name: Install pip and virtualenv
  sudo: true
  easy_install: name={{ item }}
  with_items:
    - pip
    - virtualenv

- name: setup the sysctl.conf
  sudo: true
  template: src=sysctl.conf 
            dest=/etc/sysctl.conf
  notify: reload sysctl

- name: setup the limits.conf
  sudo: true
  template: src=limits.conf 
            dest=/etc/security/limits.conf
  notify: reload sysctl
